kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Values.namespace  }}
  labels:
    app: python
spec:
  #host: my-moqaddas-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
  to:
    kind: Service
    name: {{ .Release.Name }}-svc
    weight: 100
  port:
    targetPort: {{ .Values.containerPort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None


