apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
    namespace: moqaddas-dev
    labels:
        app: python
spec:
    selector:
        app: python
    ports:
        - port: {{ .Values.servicePort }}
          protocol: TCP
          targetPort: {{ .Values.containerPort }}

